SLT-802: Nginx: Logging: Access: Format: JSONify
wunderio/simple-project-k8s pull request #38
Opened 2022-11-17 12:43 UTC by ragnarkurmwunder

See the description in [SLT-802](https://wunder.atlassian.net/browse/SLT-802).

Problem: Nginx logs are in a native format which is not very good for automated processing.
Solution: Convert the logs into JSON.

The JSON log can be turned on by the following settings:

```yml
logging:
  format: json
```

[SLT-802]: https://wunder.atlassian.net/browse/SLT-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-03-14 08:16 UTC, Rade333 requested changes
The same that Janis said in this review applies to this PR:

https://github.com/wunderio/drupal-project-k8s/pull/557#pullrequestreview-1188032718

2023-07-03 15:46 UTC, Jancis approved these changes
Looks good, thanks for white space formatting fixes. Only change I'd request is reducing comment lines in values.yaml as much as possible, down to 1-2 lines.
Logging options can be a separate, extended section in [documentation PR](https://github.com/wunderio/silta/pull/78).

2023-07-03 15:47 UTC, Jancis requested changes
whoops, clicked accept by accident

2023-08-29 08:42 UTC, closed without merging

2023-08-29 08:42 UTC, Rade333 commented
We agreed on a compromise where the original log format is kept, but a few additional details are added to the end of it.

@ragnarkurmwunder please create a new PR for that, I'm closing this one.