pod SA, disable automount SA tokens
wunderio/simple-project-k8s pull request #62
Opened 2024-12-11 19:08 UTC by Jancis

- Dedicated serviceaccount for most pods
- Disable automounting SA tokens

2025-01-20 14:28 UTC, Rade333 requested changes

2025-01-20 14:28 UTC, Rade333 commented on charts/simple/templates/deployment.yaml
> +      serviceAccountName: {{ include "simple.serviceAccountName" . }}
Why does this not replace line 134 (imagepullsecrets) like it does in the drupal-project-k8s PR?

2025-01-21 09:13 UTC, Jancis commented on charts/simple/templates/deployment.yaml
> +      serviceAccountName: {{ include "simple.serviceAccountName" . }}
fixed now

2025-01-21 09:20 UTC, Rade333 approved these changes

2025-01-21 09:20 UTC, merged